### ISSUE TITLE
AppImage update information

### ISSUE THREAD

**Issue by maggu2810** [JeodC/dxx-rebirth-compat#2]
It seems you kept the "gh-releases-zsync" update information for generated AppImage files, but you missed to change the update information to fit to your releases.
If an user of the AppImage you generate uses the AppImage update mechanism the AppImages will be replaced by mines.

**Comment by maggu2810** [comment]
Another point: If you will maintain the merge of the upstream changes and keep the builds running (fixing things like the "recently" broken MacOS build), I will archive my repo.
There should be no need for unofficial releases but if there is one, it does not make sense to provide multiple similar ones.

**Comment by JeodC** [comment]
I have no clue how .zsyncs work, so thanks for the info. I'll either fix them or not use zsync files at all.

I am hoping vLKp will use the yaml upstream. It would benefit him most as he does the code optimizations. I originally only forked to create a compatibility build for retro handhelds.

**Comment by maggu2810** [comment]
> I have no clue how .zsyncs work, so thanks for the info. I'll either fix them or not use zsync files at all.

As you decided to remove the update support, I will keep at least my AppImage builds running. Just if you wonder why I not archive my repo.

**Comment by JeodC** [comment]
> > I have no clue how .zsyncs work, so thanks for the info. I'll either fix them or not use zsync files at all.
> 
> As you decided to remove the update support, I will keep at least my AppImage builds running. Just if you wonder why I not archive my repo.

I meant no offense by taking on your workflows, by the way. I just wanted to fix them up and try to get vLKp to use them.
